### ISSUE TITLE
Launching Application

### ISSUE THREAD

**Issue by jjkilpatrick** [bakerframework/baker-android-refactor#2]
Hi,

I'm stuck on actually launching baker on my test device. Is there a default Activity? 

Thanks

**Comment by tobiasstrebitzer** [comment]
Hi @jjkilpatrick,

this repository is not yet stable, and the problem you encountered is probably fixed in an update we're rolling out next week. We've just published our first app based on the new update, [here](https://play.google.com/store/apps/details?id=com.soccertraining.magazine&hl=en). If you can wait for another week, i'll reach out to you when we've pushed the update.

To answer your question:
the default activity is [SplashActivity](https://github.com/bakerframework/baker-android-refactor/blob/1531569b24b60e837454a7b01dc101535971b5f9/Baker/src/main/AndroidManifest.xml#L41)

Also, make sure that your project directory name is "baker-android-refactor".

**Comment by tobiasstrebitzer** [comment]
Hi @jjkilpatrick, we've just pushed a big update to this repository. Have a look at the [Installation Guide](https://github.com/bakerframework/baker-android-refactor/wiki/Tutorial---Installation-Guide).

Please re-open this issue if you still have any problems launching the app.
